name: Bot API Compiler

on:
  workflow_dispatch:

jobs:
  debug-builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare for Compilation
        run: |
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt-get install make git zlib1g-dev libssl-dev gperf cmake g++
          git config --global user.name "XelXen"
          git config --global user.email "78258352+XelXen@users.noreply.github.com"
          git config --global credential.helper store
          echo "https://XelXen:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
          git clone --recursive https://github.com/tdlib/telegram-bot-api.git
          cd telegram-bot-api
          rm -rf build
          mkdir build
          cd build

      - name: Patch and Compile
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=.. ..
          cmake --build . --target install

      - name: Binary Archive
        run: |
          cd ../..
          git clone https://github.com/LibreTubeAlpha/Telegram-BotAPI bot-api
          rm -rf bot-api/*
          mv ./telegram-bot-api/bin/telegram-bot-api ./bot-api/exec
          cd bot-api
          git add -f *
          git commit -m "WORKFLOW: BUILD BINARIES"
          git push -u